
api: "https://data.geo.admin.ch/api/stac/v1/"
data: "mnt/nwp2"
nwp:
  parameters:
    - "VMAX_10M"
    - "U_10M"
    - "V_10M"
    - "T_2M"
    - "TD_2M"
    - "HZEROCL"
    - "DURSUN"
    - "PMSL"
    - "TOT_PREC"
  models:
    ICON1:
      name: "ogd-forecasting-icon-ch1"
      start: 0
      stop: 34
      freq: 3
      distance: 0.01
    ICON2:
      name: "ogd-forecasting-icon-ch2"
      start: 34
      stop: 121
      freq: 6
      distance: 0.02
  regrid:
    xmin: 5.303
    xmax: 11.003
    ymin: 45.303
    ymax: 48.003
